website/auth.py
from flask import Blueprint, render_template, request,redirect,url_for,make_response,after_this_request,session
import subprocess
from website import db_connection
from website import password_hash
import random
import string
from datetime import datetime,timedelta

auth = Blueprint('auth',__name__)

def mix_string_with_random(string_to_mix, random_length):
    random_chars = ''.join(random.choices(string.ascii_letters + string.digits, k=random_length))
    mixed_string = ''.join(random.sample(string_to_mix + random_chars, len(string_to_mix + random_chars)))
    return mixed_string.replace(' ','')

def send_password_to_the_mail(mail,pwd):
    # Command to execute
    command = r"""(echo "Subject: Partner Ledger Account"; echo "MIME-Version: 1.0"; 
    echo "Content-Type: text/html"; echo ""; echo "<h1>Mudon Maung Maung Software Team</h1><h4>
    Authentication Password for Partner Ledger Account</h4><p>Your Password is *** <b>{}</b> ***</p>
    <br><i>Don't Share this password to anyone!!</i>") | /usr/sbin/sendmail -f mdmm.softwareteam@gmail.com -F   "MMM Software Team" {} -s "Partner Ledger Account Confirmation"  """.format(pwd,mail)

    # Execute the command
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    
    # Check the command output and return code
    if result.returncode == 0:
        print(command)
    else:
        print("Command failed.")
        print("Error:")
        print(result.stderr)


@auth.route("/")
@auth.route("<atyp>")
@auth.route("<atyp>/<mgs>")
def authenticate(atyp='log',mgs=None):
    session.pop('ledger_id', default=None)
    session.pop('ledger_admin', default=None)    
    return render_template("authenticate.html",mgs=mgs,atyp = atyp)

@auth.route('/delete-cookie-for-logout')
def delete_cookie_for_logout():
    print("session deleted")
    session.pop('ledger_id', default=None)
    session.pop('ledger_admin', default=None)

@auth.route("handle-auth/<typ>",methods=['GET','POST'])
def handle_auth(typ):
    session.pop('ledger_id', default=None)
    session.pop('ledger_admin', default=None)
    if request.method == 'POST':
        conn = db_connection()
        cur = conn.cursor()
        if typ == 'log':
            code = request.form.get('log-code')
            pwd = request.form.get('log-pwd')
            cur.execute("SELECT pwd,admin FROM user_auth WHERE code = %s",(code,))
            datas = cur.fetchall()
            
            if datas != []:
                try:
                    decrypted_pwd = password_hash.A3Decryption().startDecryption(datas[0][0])
                    if decrypted_pwd == pwd:
                        session['ledger_id'] = code
                        session['ledger_admin'] = str(datas[0][1])
                        return redirect(url_for('views.all_partners'))
                except:
                    pass
            return redirect(url_for('auth.authenticate',atyp=typ,mgs="Authentication Failure..."))
        elif typ == 'reg':
            code = request.form.get('reg-code')
            u_name = request.form.get('reg-name')
            mail = request.form.get('reg-mail')
            ref = request.form.get('reg-ref')
            cur.execute("""SELECT code FROM user_auth WHERE code = %s""",(code,))
            check = cur.fetchall()
            if check != []:
                return redirect(url_for('auth.authenticate',atyp=typ,mgs="Employee Code Already Registred..."))
            cur.execute("""SELECT ptn.name 
                FROM res_users userr
                LEFT JOIN res_partner ptn ON ptn.id = userr.partner_id
                WHERE userr.login = %s;""",('MD-'+code,))
            name = cur.fetchall()
            if name == [] or not name[0][0].strip().startswith(u_name):
                return redirect(url_for('auth.authenticate',atyp=typ,mgs="Invalid Employee Code..."))
            cur.execute("""SELECT id FROM res_partner WHERE name = %s;""",(ref.strip(),))
            idd = cur.fetchall()
            if idd == [] or ref.strip() == name[0][0]:
                return redirect(url_for('auth.authenticate',atyp=typ,mgs="Invalid Reference Person from MMM.."))
            pwd = mix_string_with_random(u_name+code,len(code))
            try:
                print(pwd)
                send_password_to_the_mail(mail,pwd)
                encrypted_pwd = password_hash.A3Encryption().start_encryption(pwd,u_name)
                cur.execute("""INSERT INTO user_auth (name,code,mail,pwd,ref_person) 
                            VALUES (%s,%s,%s,%s,%s)""",(u_name,code,mail,encrypted_pwd,ref)) 
                conn.commit()
                mgs = 'Account Credentials are succesfully sent to your email'
                return redirect(url_for('auth.authenticate',atyp='log',mgs=mgs))
            except:
                return redirect(url_for('auth.authenticate',atyp=typ,mgs = "Database Insertion Error"))                      
        elif typ == 'fog':
            mail = request.form.get('forget-mail')
            code = request.form.get('forget-code')
            ref = request.form.get('forget-ref')
            cur.execute("SELECT mail,name,ref_person FROM user_auth WHERE code = %s",(code,))
            datas = cur.fetchall()
            if datas != []:
                if datas[0][0] == mail and datas[0][2] == ref:
                    # sent email
                    pwd = mix_string_with_random(datas[0][1]+code,len(code))
                    print(pwd)
                    send_password_to_the_mail(mail,pwd)
                    encrypted_pwd = password_hash.A3Encryption().start_encryption(pwd,datas[0][1])
                    cur.execute("UPDATE user_auth SET pwd = %s WHERE code = %s",(encrypted_pwd,code))
                    conn.commit()
                    return redirect(url_for('auth.authenticate',atyp='log',mgs = "New Password is successfully sent to your mail.."))     
            return redirect(url_for('auth.authenticate',atyp=typ,mgs = "Employee Code or Reference Person doesn't match with your mail.."))
        elif typ == 'out':
            respon = delete_cookie_for_logout()
            return redirect(url_for('auth.authenticate',atyp='log',mgs = "Successfully Logout!!"))  

        cur.close()
        conn.close()
    return redirect(url_for('auth.authenticate'))

website/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authenticate</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
</head>
<body>
    {% if not authenticate %}
    <div class="form-holder">
        <form class="auth-form" id="login-form" method="POST" action="{{ url_for('admin.admin_login')}}">
            <div class="mb-2">
                <label for="log-code" class="form-label">Employee Code</label>
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon3">MD - </span>
                    <input type="number" min="1" class="form-control" name="log-code" id="log-code" aria-describedby="basic-addon3 basic-addon4" required>
                </div>
                <div class="form-text text-secondary" id="basic-addon4">This code verifies that you are under MMM..</div>
            </div>
            <div class="mb-3">
                <label for="log-pwd" class="form-label">Password</label>
                <input type="password" class="form-control" name="log-pwd" id="log-pwd" required>
            </div>
            <button type="submit" class="btn btn-primary d-block w-100">Login</button>
        </form>
    </div>
    {% elif authenticate %}
    <h1 class="text-center">User Table</h1>
    <!-- search bar -->
    <div class="row justify-content-end me-3 py-3" id="search-bar">
        <div class="col-4">
            <div class="input-group">
                <input type="text" class="form-control" onkeyup="findUsers(this)" placeholder="Search">
                <span class="input-group-text" id=""><i class="fa-solid fa-magnifying-glass"></i></span>
            </div>
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Emp.Code</th>
                <th>Name</th>
                <th>Email</th>
                <th>Admin</th>
                <th>Access Rights</th>
                <th>Del.Acc.</th>
            </tr>
        </thead>
        <tbody>
            {% for data in result %}
            <tr>
                <td>MD - {{data[1]}}</td>
                <td class="username">{{data[2]}}</td>
                <td>{{data[3]}}</td>
                <td>
                    {{data[4]}}
                    {% if data[4] == True %}
                        <button class="btn btn-danger ms-1" onclick="grantAdmin('{{data[0]}}',false)">Rmv.</button>
                    {% else %}
                        <button class="btn btn-dark ms-1" onclick="grantAdmin('{{data[0]}}',true)">Add.</button>
                    {% endif %}
                </td>
                <td>
                    <button class="btn btn-primary" unit-access-data="{{data[5]}}" shop-access-data="{{data[6]}}" onclick="openForm('{{data[0]}}',this)">Grant</button>
                </td>
                <td>
                    <form action="/admin/delUser" method="POST">
                        <input value="{{data[0]}}" name="delUserId" hidden>
                        <button class="btn btn-danger"  type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- The Modal -->
    <div id="myModal" class="modal-admin">
        <!-- Modal content -->
        <div class="modal-content-admin">
            <div>
                <span class="close">&times;</span>
            </div>
            <div class="row">
                <form action="/admin/grant" method="POST">
                    <input hidden name="userID">
                    <div class="col-75 mb-2" id="selectBoxOne" style="height: 200px;overflow: auto;border: 1px solid grey;border-radius: 5px;">
                        <input hidden id="unit-list-input" name="unit-list-input">
                        {% for id,name in all_units.items() %}
                            <div class="d-flex justify-content-between px-4">
                                <span value="{{id}}">{{name}}</span><input type="checkbox">
                            </div>
                            <hr class="m-0">
                        {% endfor %}
                    </div>
                    <div class="col-75" id="selectBoxTwo" style="height: 200px;overflow: auto;border: 1px solid grey;border-radius: 5px;">
                        <input hidden id="shop-list-input" name="shop-list-input">
                        {% for id,name in all_shops.items() %}
                            <div class="d-flex justify-content-between px-4">
                                <span value="{{id}}">{{name}}</span><input type="checkbox">
                            </div>
                            <hr class="m-0">
                        {% endfor %}
                    </div>
                    <button type="" id="grandUserBtn" class="btn btn-dark mt-3" onclick="grantUser(this)">Grant Access to Users..</button>
                </form>
            </div>
        </div>
    </div>
    <p class="text-end m-3"><a class="link-opacity-100" href="{{url_for('views.all_partners')}}">Go Back To Reports</a></p>
    {% endif %}

    <script src="{{url_for('static',filename='js/main.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

website/templates/authenticate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authenticate</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
</head>
<body>
    {% if mgs %}
        <div class="alert alert-danger m-0" role="alert">{{mgs}}</div>
    {% endif %}
    <div class="form-holder">
        {% if atyp == 'log' %}
        <form class="auth-form" id="login-form" method="POST" action="{{ url_for('auth.handle_auth',typ='log')}}">
            <div class="mb-2">
                <label for="log-code" class="form-label">Employee Code</label>
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon3">MD - </span>
                    <input type="number" min="1" class="form-control" name="log-code" id="log-code" aria-describedby="basic-addon3 basic-addon4" required>
                </div>
                <div class="form-text text-secondary" id="basic-addon4">This code verifies that you are under MMM..</div>
            </div>
            <div class="mb-3">
                <label for="log-pwd" class="form-label">Password</label>
                <input type="password" class="form-control" name="log-pwd" id="log-pwd" required>
            </div>
            <button type="submit" class="btn btn-primary d-block w-100">Login</button>
            <a href="{{url_for('auth.authenticate',atyp='reg')}}" class="btn btn-secondary mt-2 w-100" role="button">Don't have an account! Register..</a>
            <a href="{{url_for('auth.authenticate',atyp='fog')}}" class="btn btn-danger mt-2 w-100" role="button">Forget Password !!</a>
        </form>
        {% elif atyp == 'fog' %}
        <form class="auth-form" id="forget-pwd-form" method="POST" action="{{ url_for('auth.handle_auth',typ='fog')}}">
            <div>
                <label for="forget-mail" class="form-label">Email</label>
                <div class="input-group">
                    <input type="email" class="form-control" name="forget-mail" id="forget-mail" aria-describedby="basic-addon3 basic-addon4" required>
                </div>
            </div>
            <div class="mb-2">
                <label for="forget-code" class="form-label">Employee Code</label>
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon3">MD - </span>
                    <input type="number" min="1" class="form-control" name="forget-code" id="forget-code" aria-describedby="basic-addon3 basic-addon4" required>
                </div>
                <div class="form-text text-secondary" id="basic-addon4">This code verifies that you are under MMM..</div>
            </div>
            <div class="mb-3">
                <label for="fog-ref" class="form-label">Ref Person in MMM</label>
                <input type="text" class="form-control" name="forget-ref" id="fog-ref" required>
            </div>
            <button type="submit" class="btn btn-primary d-block w-100">Request Password</button>
            <div class="text-center" style="cursor: pointer;">
                <a class="link-underline-opacity-10-hover" data-bs-toggle="modal" data-bs-target="#exampleModal">Terms & Conditions</a>
            </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Mudon Maung Maung Co.,Ltd</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>To prevent some security risks , we don't give user permission to create their own passoword.</p>
                        </br><p>But new password will be sent to your mail. You can change later.</p>
                        </br><p>As this is a reporting app and information are very sensitive , we surely take care of user acess rights.</p>
                        </br><p>Any newly created user won't create report for the security. But you can ask our admin to get report access. ..</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">I Agree!</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% else %}
        <form class="auth-form" id="register-form" method="POST" action="{{ url_for('auth.handle_auth',typ='reg')}}">
            <div>
                <label for="reg-name" class="form-label">Full Name</label>
                <div class="input-group">
                    <input type="text" class="form-control" name="reg-name" id="reg-name" aria-describedby="basic-addon3 basic-addon4" required>
                </div>
            </div>
            <div class="mb-2">
                <label for="reg-code" class="form-label">Employee Code</label>
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon3">MD - </span>
                    <input type="number" min="1" class="form-control" name="reg-code" id="reg-code" aria-describedby="basic-addon3 basic-addon4" required>
                </div>
                <div class="form-text text-secondary" id="basic-addon4">This code verifies that you are under MMM..</div>
            </div>
            <div>
                <label for="reg-mail" class="form-label">Email</label>
                <input type="email" class="form-control" name="reg-mail" id="reg-mail" required>
            </div>
            <div class="mb-3">
                <label for="reg-ref" class="form-label">Ref Person in MMM</label>
                <input type="text" class="form-control" name="reg-ref" id="reg-ref" required>
            </div>
            <button type="submit" class="btn btn-primary d-block w-100">Register</button>
            <a href="{{url_for('auth.authenticate',atyp='log')}}" class="btn btn-secondary mt-2 w-100" role="button">Already have an account? Login..</a>
            <div class="text-center" style="cursor: pointer;">
                <a class="link-underline-opacity-10-hover" data-bs-toggle="modal" data-bs-target="#exampleModal">Terms & Conditions</a>
            </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Mudon Maung Maung Co.,Ltd</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>When you request forget password , new password will be sent to your email.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">I Agree!</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% endif %}
    </div>    
    <script src="{{url_for('static',filename='js/main.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>